author: PARK Yeonkyu
date: '2022-02-20'
baseurl: https://yeonkyupark.github.io/
languageCode: ko-KR
title: YK logs
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: 'yeonkyupark-github-io'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
hasCJKLanguage: true
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://yeonkyupark.github.io/
    - name: Instagram
      url: https://www.instagram.com/yeonkyu.park/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
